### ISSUE TITLE
[BUG] while using .deezer error occuring

### ISSUE THREAD

**Issue by Rawana07** [DevsExpo/FridayUserbot#306]
## Checklist
- [y ] I Am Using Latest Version.
- [ y] I have searched Issues And Pull Requests And I Confirm That This is Not A Duplicate Issue.

## Command Which Causes This Issue.
Command Name, Filename, And Function name.
.deezer
## Description
A detailed description of the Bug.
!ERROR - REPORT!

Trace Back : Traceback (most recent call last):
  File "/main_startup/core/decorators.py", line 71, in wrapper
    await func(client, message)
  File "/plugins/stream_tools.py", line 200, in deezer
    datto = requests.get(url=urlp).json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Plugin-Name : plugins.stream_tools
Function Name : deezer 
Date : 2021-04-02 
Time : 18:00:14

You can Forward This to @FridayChat, If You Think This is Serious A Error!

## Traceback
TraceBack Of Bug (if any)
!ERROR - REPORT!

Trace Back : Traceback (most recent call last):
  File "/main_startup/core/decorators.py", line 71, in wrapper
    await func(client, message)
  File "/plugins/stream_tools.py", line 200, in deezer
    datto = requests.get(url=urlp).json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Plugin-Name : plugins.stream_tools
Function Name : deezer 
Date : 2021-04-02 
Time : 18:00:14

You can Forward This to @FridayChat, If You Think This is Serious A Error!

**Comment by StarkGang** [comment]
https://github.com/DevsExpo/FridayUserbot/commit/783e4c939fc4399dfb548c00a805af7044370662

Fixed. Thank You For Informing Us.
